#!/bin/sh

uci -q batch <<-EOF >"/dev/null"
	delete firewall.homeproxy_pre
	set firewall.homeproxy_pre=include
	set firewall.homeproxy_pre.type=nftables
	set firewall.homeproxy_pre.path="/var/run/homeproxy/fw4_pre.nft"
	set firewall.homeproxy_pre.position="table-pre"

	delete firewall.homeproxy_post
	set firewall.homeproxy_post=include
	set firewall.homeproxy_post.type=nftables
	set firewall.homeproxy_post.path="/var/run/homeproxy/fw4_post.nft"
	set firewall.homeproxy_post.position="table-post"
	commit firewall
EOF

exit 0
