#!/bin/sh
[ -z "${IPKG_INSTROOT}" ] || exit 0

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@easymesh[-1]
	add ucitrack easymesh
	set ucitrack.@easymesh[-1].init=easymesh
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
