#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/bin/serverchand/serverchand"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/bin/serverchand/serverchand &
	fi
	echo "serverchand is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/serverchand/serverchand"` 2>/dev/null
	echo "serverchand exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}
