#!/bin/sh /etc/rc.common
START=99
STOP=30

enable=$(uci get easymesh.config.enabled 2>/dev/null)
mesh_bat0=$(uci get network.bat0 2>/dev/null)
mesh_nwi_mesh0=$(uci get network.nwi_mesh0 2>/dev/null)
mesh_mesh0=$(uci get wireless.mesh0 2>/dev/null)
ap_mode=$(uci get easymesh.config.ap_mode 2>/dev/null)
lan=$(uci get network.lan.ifname 2>/dev/null)
ipaddr=$(uci get easymesh.config.ipaddr 2>/dev/null)
netmask=$(uci get easymesh.config.netmask 2>/dev/null)
gateway=$(uci get easymesh.config.gateway 2>/dev/null)
#ap_gateway=$(uci get network.lan.gateway 2>/dev/null)
dns=$(uci get easymesh.config.dns 2>/dev/null)
mesh_id=$(uci get easymesh.config.mesh_id 2>/dev/null)
interface=$(uci get easymesh.config.interface 2>/dev/null)
mesh0_interface=$(uci get wireless.mesh0.device 2>/dev/null)
encryption=$(uci get easymesh.config.encryption 2>/dev/null)
key=$(uci get easymesh.config.key 2>/dev/null)

start(){	
	if [ $enable -eq 1 ]; then
		if [ x$mesh_bat0 != x"interface" ]; then
			uci set network.bat0=interface
			uci set network.bat0.proto='batadv'
			uci set network.bat0.routing_algo='BATMAN_IV'
			uci set network.bat0.aggregated_ogms='1'
			#uci set network.bat0.gw_bandwidth='10000/2000'
			uci set network.bat0.ap_isolation='0'
			uci set network.bat0.bonding='0'
			uci set network.bat0.fragmentation='1'
			uci set network.bat0.gw_mode='off'
			#uci set network.bat0.gw_sel_class='20'
			uci set network.bat0.log_level='0'
			uci set network.bat0.orig_interval='1000'
			uci set network.bat0.bridge_loop_avoidance='1'
			uci set network.bat0.distributed_arp_table='1'
			uci set network.bat0.multicast_mode='1'
			uci set network.bat0.network_coding='0'
			uci set network.bat0.hop_penalty='30'
			uci set network.bat0.isolation_mark='0x00000000/0x00000000'
			
			uci add_list network.lan.ifname='bat0'
			uci commit network
		fi

		if [ x$mesh_nwi_mesh0 != x"interface" ]; then
			uci set network.nwi_mesh0=interface
			uci set network.nwi_mesh0.proto='batadv_hardif'
			uci set network.nwi_mesh0.mtu='2304'
			uci set network.nwi_mesh0.master='bat0'
			uci commit network
		fi

		if [ x$mesh_mesh0 != x"wifi-iface" ]; then
			uci set wireless.mesh0=wifi-iface
			uci set wireless.mesh0.device=$interface
			uci set wireless.mesh0.ifname='mesh0'
			uci set wireless.mesh0.network='nwi_mesh0'
			uci set wireless.mesh0.mode='mesh'
			uci set wireless.mesh0.mesh_fwding='0'
			uci set wireless.mesh0.mesh_id=$mesh_id
			uci commit wireless
		fi
		if [ x$mesh_mesh0 = x"wifi-iface" ]; then
			if [ x$mesh0_interface != x$interface ]; then
				uci set wireless.mesh0.device=$interface
				uci commit wireless
			fi
		fi

		if [ $encryption -ne 1 ]; then
			uci set wireless.mesh0.encryption='none'
			uci commit wireless
		else
			uci set wireless.mesh0.encryption='sae'
			uci set wireless.mesh0.key=$key
			uci commit wireless
		fi

		if [ $ap_mode -eq 1 ]; then
			uci set network.lan.ipaddr=$ipaddr
			uci set network.lan.netmask=$netmask
			uci set network.lan.gateway=$gateway
			uci set network.lan.dns=$dns
			uci commit network
			
			uci set dhcp.lan.dynamicdhcp='0'
			uci delete dhcp.lan.ra
			uci delete dhcp.lan.dhcpv6
			uci delete dhcp.lan.ra_management
			uci commit dhcp

			/etc/init.d/odhcpd stop && /etc/init.d/odhcpd disable
			/etc/init.d/firewall stop && /etc/init.d/firewall disable
			/etc/init.d/network restart
		else
			uci delete network.lan.gateway
			uci delete network.lan.dns
			uci commit network

			uci delete dhcp.lan.dynamicdhcp
			uci commit dhcp

			/etc/init.d/odhcpd enable && /etc/init.d/odhcpd start
			/etc/init.d/firewall enable && /etc/init.d/firewall start
			/etc/init.d/network restart
		fi
			#batctl add if mesh0
			#brctl addif br-lan bat0 
			#ifconfig bat0 up
	fi
}

stop(){
	if [ $enable -ne 1 ]; then
		if [ x$mesh_bat0 = x"interface" ]; then
			uci delete network.bat0
			uci del_list network.lan.ifname='bat0'
			uci commit network
		fi

		if [ x$mesh_nwi_mesh0 = x"interface" ]; then
			uci delete network.nwi_mesh0
			uci commit network
		fi

		if [ x$mesh_mesh0 = x"wifi-iface" ]; then
			uci delete wireless.mesh0
			uci commit wireless
		fi

		if [ $ap_mode -ne 1 ]; then
			uci delete network.lan.gateway
			uci delete network.lan.dns
			uci commit network

			uci delete dhcp.lan.dynamicdhcp
			uci commit dhcp

			/etc/init.d/odhcpd enable && /etc/init.d/odhcpd start
			/etc/init.d/firewall enable && /etc/init.d/firewall start
			/etc/init.d/network restart
		fi
	fi
}

restart() {
	stop
	start
}
