#!/bin/sh

rm -Rf /var/luci-modulecache
rm -Rf /var/luci-indexcache
uci batch <<-EOF
	set luci.themes.Opentopd=/luci-static/opentopd
	set luci.main.mediaurlbase=/luci-static/opentopd
	commit luci
EOF
exit 0
