#!/bin/sh /etc/rc.common
# Copyright (C) 2025 ImmortalWrt.org
# SPDX-License-Identifier: Apache-2.0

USE_PROCD=1
START=99
STOP=10

_append_arg() {
	procd_append_param command "$1"
}

start_service() {
	local enabled config_file

	config_load "gost"
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq 0 ] && return 0

	config_get config_file "config" "config_file" ""

	procd_open_instance "instance1"
	procd_set_param command /usr/bin/gost

	if [ -n "$config_file" ] && [ -f "$config_file" ]; then
		procd_append_param command -C "$config_file"
	fi

	config_list_foreach "config" "arguments" _append_arg

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "gost"
}
