#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Material3 >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Material3=/luci-static/material3
		set luci.main.mediaurlbase=/luci-static/material3
  	        set luci.themes.Material3Blue=/luci-static/material3-blue
	        set luci.themes.Material3Green=/luci-static/material3-green
	        set luci.themes.Material3Red=/luci-static/material3-red
		commit luci
	EOF
fi

exit 0