#!/bin/sh

echo "config basic 'config'" >/etc/config/ddns-go

chmod +x /usr/share/rpcd/ucode/luci.ddns-go
chown root:www-data /usr/libexec/ddns-go-call
chmod 750 /usr/libexec/ddns-go-call
rm -f /tmp/luci-indexcache

exit 0
