#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci batch <<-EOF
		set luci.themes.OpenWrt2020=/luci-static/openwrt2020
		set luci.main.mediaurlbase=/luci-static/openwrt2020
		commit luci
	EOF
fi

exit 0
