#!/bin/sh /etc/rc.common

START=99
STOP=90
USE_PROCD=1

start_service() {
	procd_open_instance
	enable_value=$(uci get wechatpush.config.enable 2>/dev/null || echo "0")
	[ "$enable_value" -ne "0" ] && procd_set_param command /usr/share/wechatpush/wechatpush && echo "wechatpush is starting now ..."
	procd_close_instance
}

reload_service() {
	stop
	sleep 1
	start
}

stop_service() {
	echo "Terminating wechatpush process..."
}

service_triggers() {
	procd_add_reload_trigger wechatpush
}
