#!/bin/sh
uci batch <<-EOF
	set luci.themes.Bootstrap_New=/luci-static/bootstrap_new
	set luci.themes.Bootstrap_Blue=/luci-static/bootstrap_blue
	set luci.main.mediaurlbase=/luci-static/bootstrap_new
	commit luci
EOF
exit 0
