#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

start_service() {
  procd_open_instance
  procd_set_param command /etc/subconverter/subconverter
  procd_set_param respawn 3600 1 3
  procd_close_instance
}