#!/bin/sh
[ -f /usr/lib/lua/luci/view/themes/ifit/out_header_login.htm ] && mv -f /usr/lib/lua/luci/view/themes/ifit/out_header_login.htm /usr/lib/lua/luci/view/header_login.htm
rm -Rf /var/luci-modulecache
rm -Rf /var/luci-indexcache
uci batch <<-EOF
	set luci.themes.ifit=/luci-static/ifit
	set luci.main.mediaurlbase=/luci-static/ifit
	commit luci
EOF
exit 0
