
config adguardhome 'config'
	option enabled '0'
	# All paths must be readable by the configured user
	option config_file '/etc/adguardhome/adguardhome.yaml'
	# Where to store persistent data by AdGuard Home
	option work_dir '/var/lib/adguardhome'
	option user 'adguardhome'
	option group 'adguardhome'
	option verbose '0'

	# Files and directories that AdGuard Home has read-only access to
	# list jail_mount '/etc/ssl/adguardhome.crt'
	# list jail_mount '/etc/ssl/adguardhome.key'

	# Files and directories that AdGuard Home has read-write access to
	# list jail_mount_rw '/path/to/dir'

	# Advanced options. Modify at your own risk.

	# More info: https://go.dev/doc/gc-guide#GOGC
	option gc '0'

	# Max number of OS threads to use
	# 0 to match the number of CPUs (default)
	# >0 to explicitly specify concurrency
	option maxprocs '0'

	# Soft memory limit in MB, 0 to disable
	option memlimit '0'
