#!/bin/sh

newpath=$(echo ":$PATH:" | sed -e 's#:/usr/libexec/istore/mirror-bin:#:#g' -e 's/^:*//' -e 's/:*$//')
[ -z "$newpath" ] && newpath="/usr/sbin:/usr/bin:/sbin:/bin"

export PATH="$newpath"

# if url starts with $IS_ORIG_SERVER, replace it with $IS_MIRROR_SERVER
if [ -n "$IS_ORIG_SERVER" ] && [ -n "$IS_MIRROR_SERVER" ]; then
    n=$#
    while [ "$n" -gt 0 ]; do
        i="$1"
        shift
        case "$i" in
            "$IS_ORIG_SERVER"/*.apk|\
            "$IS_ORIG_SERVER"/*.ipk)
                i="$IS_MIRROR_SERVER/${i#$IS_ORIG_SERVER/}"
                ;;
        esac
        set -- "$@" "$i"
        n=$((n - 1))
    done
fi
export -n IS_ORIG_SERVER IS_MIRROR_SERVER

exec curl "$@"
