#!/bin/sh

bing_background="$(uci -q get "argone.@global[0].bing_background")"
[ -n "$bing_background" ] || exit 0

if [ "$bing_background" = "1" ]; then
	uci -q set "argone.@global[0].online_wallpaper"="bing"
else
	uci -q set "argone.@global[0].online_wallpaper"="none"
fi
uci -q delete "argone.@global[0].bing_background"
uci -q commit "argone"

exit 0
